from datetime import date, datetime
from typing import Optional

from sqlmodel import Field, SQLModel


class StockUniverse(SQLModel, table=True):
    """Known stocks that have been researched at least once."""

    __tablename__ = "stock_universe"

    id: Optional[int] = Field(default=None, primary_key=True)
    ticker: str = Field(unique=True, index=True)
    name: Optional[str] = None
    sector: Optional[str] = None
    added_at: datetime = Field(default_factory=datetime.utcnow)


class WatchlistItem(SQLModel, table=True):
    """Stocks flagged as interesting candidates, not yet purchased."""

    __tablename__ = "watchlist_item"

    id: Optional[int] = Field(default=None, primary_key=True)
    ticker: str = Field(index=True)
    added_at: datetime = Field(default_factory=datetime.utcnow)
    reason: Optional[str] = None
    # active | converted (became a position) | dropped
    status: str = Field(default="active")


class Position(SQLModel, table=True):
    """Stocks currently held or previously held."""

    __tablename__ = "position"

    id: Optional[int] = Field(default=None, primary_key=True)
    ticker: str = Field(index=True)
    shares: float
    entry_price: float
    entry_date: date
    exit_price: Optional[float] = None
    exit_date: Optional[date] = None
    # open | closed
    status: str = Field(default="open", index=True)
    target_price: Optional[float] = None
    stop_loss: Optional[float] = None
    note: Optional[str] = None


class ResearchReport(SQLModel, table=True):
    """Output from the Research Agent for a single ticker in a scan batch."""

    __tablename__ = "research_report"

    id: Optional[int] = Field(default=None, primary_key=True)
    run_id: str = Field(index=True)  # UUID grouping a scan batch
    ticker: str = Field(index=True)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    raw_data: Optional[str] = None   # JSON blob of gathered market data
    analysis: Optional[str] = None  # LLM-generated narrative
    score: Optional[float] = None   # 0.0–10.0 composite score
    score_breakdown: Optional[str] = None  # JSON: {momentum, fundamentals, catalyst, technical}
    thesis: Optional[str] = None
    entry_zone: Optional[str] = None   # e.g. "860-880"
    target_price: Optional[float] = None
    stop_loss: Optional[float] = None
    time_horizon: Optional[str] = None
    key_risks: Optional[str] = None    # JSON array


class InvestmentProposal(SQLModel, table=True):
    """Buy/sell/hold recommendation from the Decision Agent."""

    __tablename__ = "investment_proposal"

    id: Optional[int] = Field(default=None, primary_key=True)
    run_id: str = Field(index=True)
    ticker: str = Field(index=True)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    # BUY | SELL | HOLD
    action: str
    # HIGH | MEDIUM | LOW
    conviction: str
    shares_suggested: Optional[float] = None
    entry_price_range: Optional[str] = None
    target_price: Optional[float] = None
    stop_loss: Optional[float] = None
    position_size_usd: Optional[float] = None
    rationale: Optional[str] = None
    key_catalysts: Optional[str] = None  # JSON array
    risk_factors: Optional[str] = None   # JSON array
    time_horizon: Optional[str] = None
    slack_sent: bool = Field(default=False)
    # pending | approved | rejected
    human_decision: str = Field(default="pending")


class ProposalResult(SQLModel, table=True):
    """Actual outcome of an InvestmentProposal — used for Reflection loop."""

    __tablename__ = "proposal_result"

    id: Optional[int] = Field(default=None, primary_key=True)
    proposal_id: int = Field(index=True, foreign_key="investment_proposal.id")
    ticker: str = Field(index=True)
    entry_price: float
    exit_price: Optional[float] = None
    exit_date: Optional[date] = None
    actual_return_pct: Optional[float] = None
    # "win" | "loss" | "neutral" | "pending"
    outcome: str = Field(default="pending")
    notes: Optional[str] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)


class MonitorAlert(SQLModel, table=True):
    """Alert generated by the Monitor Agent for an open position."""

    __tablename__ = "monitor_alert"

    id: Optional[int] = Field(default=None, primary_key=True)
    position_id: Optional[int] = Field(default=None, foreign_key="position.id")
    ticker: str = Field(index=True)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    # SELL_SIGNAL | STOP_LOSS | TARGET_REACHED | NEWS_EVENT | DAILY_SUMMARY
    alert_type: str
    # HIGH | MEDIUM | LOW
    severity: str
    current_price: Optional[float] = None
    unrealized_pnl_pct: Optional[float] = None
    message: str
    reasoning: Optional[str] = None
    updated_stop_loss: Optional[float] = None
    slack_sent: bool = Field(default=False)
